export const ERROR_MESSAGE = {
	ERR00005: "Không tìm thấy dữ liệu nào",
	ERR00008: "Phải có ít nhất một quản trị viên hoạt động",
	ERR00009: "Mật khẩu và xác nhận mật khẩu không khớp",
	ERR00010: "Tên đăng nhập đã tồn tại!",
	ERR00011: "Email đã tồn tại!",
	ERR00012: "Tên đăng nhập không được cập nhật",
	ERR00013: "Nhóm không được cập nhật",
	ERR00014: "Người dùng đang hoạt động",
	ERR00015: "Ảnh đại diện không hợp lệ",
	ERR00016: "Email của quản trị viên là bắt buộc",
	ERR00017: "Định dạng số điện thoại là 7-13 ký tự số",
	ERR00018: "Có học sinh không tồn tại hoặc không hoạt động",
	ERR00019: "Giáo viên không tồn tại hoặc không hoạt động",
	ERR00020: "Icon không hợp lệ",
	ERR00021: "Ảnh nền không hợp lệ",
	ERR00022: "Không thể chuyển trạng thái của học sinh đang trong phòng chơi",
	ERR00023: "Không thể chuyển trạng thái của học sinh đang trong phòng chơi",
	ERR00024: "Không thể chuyển trạng thái của giáo viên đang có phòng chơi",
	ERR00025: "Không thể chuyển trạng thái của giáo viên đang có phòng chơi",
	ERR00026: "Không thể sửa, xóa lớp học đang có phòng chơi",
	ERR00027: "Không thể sửa, xóa lớp học đang có phòng chơi",
	ERR00028: "Không thể xoá thẻ đang được dùng trong phòng chơi",
	ERR00029: `Có phòng chơi đang sử dụng luật chơi này!`,
	ERR00030: "Không thể xoá nhóm thẻ đã có thẻ chơi",
	ERR00031: "Tên không dược để trống",
	ERR00032: "Cần ít nhất 5 thẻ mỗi loại (tài sản, tiêu sản, may mắn)",
	ERR00033: "Cần ít nhất 5 thẻ mỗi loại (tài sản, tiêu sản, may mắn)",
	ERR00034: "Cần ít nhất 5 thẻ mỗi loại (tài sản, tiêu sản, may mắn)",
	ERR00037: "Nhóm thẻ đã tồn tại!",
};
